version: '3.8'

services:
  trading-bot:
    build: .
    container_name: hyperliquid-trading-bot
    restart: unless-stopped
    ports:
      - "3000:3000"  # Dashboard
      - "3001:3001"  # Metrics
      - "3002:3002"  # Health check
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env:ro
    depends_on:
      - redis
      - prometheus
    networks:
      - trading-network

  redis:
    image: redis:7-alpine
    container_name: trading-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - trading-network

  prometheus:
    image: prom/prometheus:latest
    container_name: trading-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - trading-network

volumes:
  redis-data:
  prometheus-data:

networks:
  trading-network:
    driver: bridge